//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"

class Pies : public Ssak {
public:
	int dlugosc_ogona;
	int kolor_siersci;
};

#endif  //_PIES_H
