//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zwierze.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Zwierze.h"

void Zwierze::stworz(int nw, int nt) {

}

