//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zwierze.h
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#if !defined(_ZWIERZE_H)
#define _ZWIERZE_H


class Zwierze {
public:
	int wielkosc;
	int typ_pokarmu;
	void stworz(int nw, int nt);
};

#endif  //_ZWIERZE_H
